--------------------------------------------------------
--  파일이 생성됨 - 수요일-9월-08-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROBLEM_TABLE_NUMBER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PROBLEM_TABLE_NUMBER" 
   (	"PROBLEM_NO" NUMBER(3,0), 
	"NUMONE" NVARCHAR2(2000), 
	"NUMTWO" NVARCHAR2(2000), 
	"NUMTHREE" NVARCHAR2(2000), 
	"NUMFOUR" NVARCHAR2(2000), 
	"ANSWER_NO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROBLEM_TABLE_NUMBER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PROBLEM_TABLE_NUMBER" MODIFY ("ANSWER_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PROBLEM_TABLE_NUMBER" MODIFY ("NUMFOUR" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PROBLEM_TABLE_NUMBER" MODIFY ("NUMTHREE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PROBLEM_TABLE_NUMBER" MODIFY ("NUMTWO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PROBLEM_TABLE_NUMBER" MODIFY ("NUMONE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PROBLEM_TABLE_NUMBER" MODIFY ("PROBLEM_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PROBLEM_TABLE_NUMBER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PROBLEM_TABLE_NUMBER" ADD CONSTRAINT "FK_PN" FOREIGN KEY ("PROBLEM_NO")
	  REFERENCES "SCOTT"."PROBLEM_TABLE" ("PROBLEM_NO") ENABLE;