--------------------------------------------------------
--  DDL for Table PROBLEM_TABLE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PROBLEM_TABLE" 
   (	"PROBLEM_NO" NUMBER(3,0), 
	"PROBLEM" NVARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PNO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PK_PNO" ON "SCOTT"."PROBLEM_TABLE" ("PROBLEM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROBLEM_TABLE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PROBLEM_TABLE" ADD CONSTRAINT "PK_PNO" PRIMARY KEY ("PROBLEM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."PROBLEM_TABLE" MODIFY ("PROBLEM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PROBLEM_TABLE" MODIFY ("PROBLEM_NO" NOT NULL ENABLE);