
--------------------------------------------------------
--  DDL for Table SKIN_TABLE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."SKIN_TABLE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"SKIN" CHAR(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SKIN_TABLE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SKIN_TABLE" MODIFY ("SKIN" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKIN_TABLE" MODIFY ("ID" NOT NULL ENABLE);